// Simple fetch-based mock for Copilot Studio backend

type HttpMethod = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";

let mockInstalled = false;

export function setupMockBackend() {
    if (mockInstalled) return;
    mockInstalled = true;

    const originalFetch = window.fetch.bind(window);

    window.fetch = async (input: RequestInfo | URL, init?: RequestInit): Promise<Response> => {
        const url = typeof input === "string" ? input : input instanceof URL ? input.toString() : input.url;
        const method: HttpMethod = ((init?.method ?? "GET").toUpperCase() as HttpMethod);

        // Helper to simulate latency
        const delay = (ms: number) => new Promise(res => setTimeout(res, ms));
        const timeStamp = now => new Date(now).toISOString();

        // ---------- /api/session/start ----------
        // if (url.endsWith("/api/session/start") && method === "POST") {
        //     await delay(400);
        //
        //     const mockStartResponse = {
        //         conversationId: "d9cf3f2b-9f40-4fc6-a061-9b7b243ca111",
        //         messages: [
        //             {
        //                 id: "reply-1",
        //                 sender: "bot",
        //                 text:
        //                     "Some data may be outside of the US FDA-approved prescribing information. In providing this data, Gilead Sciences, Inc. is not making any representation as to its clinical relevance or to the use of any Gilead product(s). For information about the approved conditions of use of any Gilead drug product, please consult the FDA-approved prescribing information.",
        //                 timestamp: timeStamp
        //             },
        //             {
        //                 id: "reply-2",
        //                 sender: "bot",
        //                 text:
        //                     "Welcome. If you would like to report an adverse event at any time, you can visit Gilead's Adverse Event Reporting portal, or call 1‑800‑GILEAD‑5 (press option #3).\n\n**Please type your question below and include a Gilead drug name.**",
        //                 timestamp: timeStamp
        //             }
        //         ]
        //     };
        //
        //     return new Response(JSON.stringify(mockStartResponse), {
        //         status: 200,
        //         headers: { "Content-Type": "application/json" }
        //     });
        // }

        if (url.endsWith("/api/session/start") && method === "POST") {
            await delay(400);

            const mockStartResponse = {
                conversationId: "bbb6398e-effb-4d82-bda3-bf7c9068cfc1",
                messages: [
                    {
                        id: "10009ddf-0205-45c4-8726-979533faab6f",
                        sender: "bot",
                        text:
                            "Hello and thank you for calling HCPBot. Please note that some responses are generated by AI and may require verification for accuracy. How may I help you today?",
                        timestamp: timeStamp,
                        isLastBotMessage: false,
                        showAvatar: true
                    },
                    {
                        id: "28c4bb72-bfad-4469-adb6-5ca7af75052b",
                        sender: "bot",
                        text:
                            "Welcome. If you would like to report an adverse event at any time, you can visit Gilead's Adverse Event Reporting portal, or call 1‑800‑GILEAD‑5 (press option #3).\n\n**Please type your question below and include a Gilead drug name.**",
                        timestamp: timeStamp,
                        isLastBotMessage: true,
                        showAvatar: false
                    }
                ]
            };

            return new Response(JSON.stringify(mockStartResponse), {
                status: 200,
                headers: { "Content-Type": "application/json" }
            });
        }

        // ---------- /api/session/send ----------
        if (url.endsWith("/api/session/send") && method === "POST") {
            await delay(500);

            let userText = "";
            try {
                if (init?.body && typeof init.body === "string") {
                    const parsed = JSON.parse(init.body);
                    userText = parsed.text ?? "";
                }
            } catch {
                // ignore parse errors
            }

            let mockSendResponse: {
                messages: ({ sender: string; id: string; text: string; timestamp: (now) => string | null; isLastBotMessage?: boolean; showAvatar?: boolean } | {
                    attachments: {
                        contentType: string;
                        content: {
                            $schema: string;
                            type: string;
                            body: ({ text: string; type: string; wrap: boolean } | {
                                isRequired: boolean;
                                errorMessage: string;
                                id: string;
                                label: string;
                                placeholder: string;
                                type: string
                            } | {
                                isRequired: boolean;
                                errorMessage: string;
                                style: string;
                                id: string;
                                label: string;
                                placeholder: string;
                                type: string
                            })[];
                            version: string;
                            actions: { type: string; title: string }[]
                        }
                    }[];
                    sender: string;
                    id: string;
                    timestamp: (now) => string | null
                })[]
            } = {
                messages: [
                    {
                        id: "reply-3",
                        sender: "bot",
                        text:
                            "Some data may be outside of the US FDA-approved prescribing information. In providing this data, Gilead Sciences, Inc. is not making any representation as to its clinical relevance or to the use of any Gilead product(s). For information about the approved conditions of use of any Gilead drug product, please consult the FDA-approved prescribing information.",
                        timestamp: timeStamp,
                        isLastBotMessage: false,
                        showAvatar: true
                    },
                    {
                        id: "reply-4",
                        sender: "bot",
                        text:
                            `You asked: "${userText || "your question"}"\n\n**Product Labeling – Hepatic Impairment**\n\nFor DRUG, no dose adjustment is recommended in patients with mild hepatic impairment (Child-Pugh A). Use with caution in patients with moderate hepatic impairment (Child-Pugh B). DRUG is not recommended in patients with severe hepatic impairment (Child-Pugh C).`,
                        timestamp: timeStamp,
                        isLastBotMessage: true,
                        showAvatar: false
                    }
                ]
            };

            const mockAdverseEventCardResponse = {
                messages: [
                    {
                        id: "msg-bot-001",
                        sender: "bot",
                        timestamp: timeStamp,
                        text: "Please fill out the following form below. We may follow-up with you about the adverse event."
                    },
                    {
                        id: "msg-bot-002",
                        sender: "bot",
                        timestamp: timeStamp,
                        attachments: [
                            {
                                contentType: "application/vnd.microsoft.card.adaptive",
                                content: {
                                    $schema: "https://adaptivecards.io/schemas/adaptive-card.json",
                                    type: "AdaptiveCard",
                                    version: "1.5",
                                    body: [
                                        {
                                            type: "TextBlock",
                                            text: "For more information on how Gilead handles your personal information, as well as rights you may have related to your personal information, please refer to the [Gilead Privacy Statement.](https://www.gilead.com/privacy-statements)",
                                            wrap: true
                                        },
                                        {
                                            type: "Input.Text",
                                            id: "firstName",
                                            label: "HCP First Name",
                                            placeholder: "Enter your first name",
                                            isRequired: true,
                                            errorMessage: "Please enter your first name"
                                        },
                                        {
                                            type: "Input.Text",
                                            id: "lastName",
                                            label: "HCP Last Name",
                                            placeholder: "Enter your last name",
                                            isRequired: true,
                                            errorMessage: "Please enter your last name"
                                        },
                                        {
                                            type: "Input.Text",
                                            id: "email",
                                            label: "HCP Email Address",
                                            placeholder: "Enter your email",
                                            style: "Email",
                                            isRequired: true,
                                            errorMessage: "Please enter a valid email address"
                                        }
                                    ],
                                    actions: [
                                        {
                                            type: "Action.Submit",
                                            title: "Submit"
                                        }
                                    ]
                                }
                            }
                        ]
                    }
                ]
            }



            if (userText.toLowerCase().includes("adverse")) {
                mockSendResponse =  mockAdverseEventCardResponse;
            }

            return new Response(JSON.stringify(mockSendResponse), {
                status: 200,
                headers: { "Content-Type": "application/json" }
            });
        }

        // ---------- /api/health (optional) ----------
        if (url.endsWith("/api/health") && method === "GET") {
            return new Response(JSON.stringify({ status: "mock-ok" }), {
                status: 200,
                headers: { "Content-Type": "application/json" }
            });
        }

        // Fallback: real network
        return originalFetch(input as any, init);
    };
}
